version: '2'
services:
    zzrot.com:
        image: zzrot/alpine-caddy
        volumes:
            -   ./Caddyfile:/etc/Caddyfile
            -   ./zzrot.com/public:/var/www/html
        networks:
            -   frontend
    blog.zzrot.com:
        image: zzrot/alpine-ghost
        networks:
          -   frontend

networks:
    frontend:
