version: '2'
services:
    proxy:
        image: zzrot/alpine-caddy
        ports:
            -   "80:80"
            -   "443:443"
        volumes:
            -   ./compose/proxy/Caddyfile:/etc/Caddyfile
            -   ./.caddy:/root/.caddy
        networks:
            - frontend

    zzrot.com:
        expose:
            -   80
    blog.zzrot.com:
        environment:
          DEV_DOMAIN: https://blog.zzrot.com
          NODE_ENV: production
        volumes:
          - blog.ghost.com/content/:/var/lib/ghost/
        expose:
            -   2368
    #jenkins.zzrot.com:
    #    image: jenkins
    #    ports:
    #      - "50000:50000"
    #    expose:
    #      - 8080
    #    volumes:
    #      - ./zzrot.com/:/var/jenkins_home
    #    environment:
    #      - JAVA_OPTS="-Xmx1024m"
    #    networks:
    #      - frontend
