version: '2'
services:
    zzrot.com:
        ports:
            -   "80:80"
    blog.zzrot.com:
        environment:
          DEV_DOMAIN: http://192.168.99.100:2368
        volumes:
          - ./blog.zzrot.com/:/var/lib/ghost/
        ports:
            -   "2368:2368"
    developer:
        build: ./compose/developer
        container_name: dev
        volumes:
            -   ./zzrot.com:/usr/src/app:rw
        working_dir: /usr/src/app
        ports:
            -   "3000:3000"
            -   "3001:3001"
        networks:
            - frontend
